<?php
// This script and data application were generated by AppGini 23.11
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/lideres.php');
	include_once(__DIR__ . '/lideres_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('lideres');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'lideres';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`lideres`.`LIDER`" => "LIDER",
		"`lideres`.`CEDULA`" => "CEDULA",
		"`lideres`.`NOMBRE`" => "NOMBRE",
		"IF(    CHAR_LENGTH(`divpol20221`.`PUESTO`) || CHAR_LENGTH(`divpol20221`.`nompue`), CONCAT_WS('',   `divpol20221`.`PUESTO`, '-', `divpol20221`.`nompue`), '') /* PUESTO */" => "PUESTO",
		"`lideres`.`CELULAR`" => "CELULAR",
		"`lideres`.`DIRECCION`" => "DIRECCION",
		"`lideres`.`CORREO`" => "CORREO",
		"`lideres`.`OBSERVACIONES`" => "OBSERVACIONES",
		"`lideres`.`ESTADO`" => "ESTADO",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`lideres`.`LIDER`" => "LIDER",
		"`lideres`.`CEDULA`" => "CEDULA",
		"`lideres`.`NOMBRE`" => "NOMBRE",
		"IF(    CHAR_LENGTH(`divpol20221`.`PUESTO`) || CHAR_LENGTH(`divpol20221`.`nompue`), CONCAT_WS('',   `divpol20221`.`PUESTO`, '-', `divpol20221`.`nompue`), '') /* PUESTO */" => "PUESTO",
		"`lideres`.`CELULAR`" => "CELULAR",
		"`lideres`.`DIRECCION`" => "DIRECCION",
		"`lideres`.`CORREO`" => "CORREO",
		"`lideres`.`OBSERVACIONES`" => "OBSERVACIONES",
		"`lideres`.`ESTADO`" => "ESTADO",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`lideres`.`LIDER`" => "LIDER",
		"`lideres`.`CEDULA`" => "CEDULA",
		"`lideres`.`NOMBRE`" => "NOMBRE",
		"IF(    CHAR_LENGTH(`divpol20221`.`PUESTO`) || CHAR_LENGTH(`divpol20221`.`nompue`), CONCAT_WS('',   `divpol20221`.`PUESTO`, '-', `divpol20221`.`nompue`), '') /* PUESTO */" => "PUESTO",
		"`lideres`.`CELULAR`" => "CELULAR",
		"`lideres`.`DIRECCION`" => "DIRECCION",
		"`lideres`.`CORREO`" => "CORREO",
		"`lideres`.`OBSERVACIONES`" => "OBSERVACIONES",
		"`lideres`.`ESTADO`" => "ESTADO",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`lideres`.`LIDER`" => "LIDER",
		"`lideres`.`CEDULA`" => "CEDULA",
		"`lideres`.`NOMBRE`" => "NOMBRE",
		"IF(    CHAR_LENGTH(`divpol20221`.`PUESTO`) || CHAR_LENGTH(`divpol20221`.`nompue`), CONCAT_WS('',   `divpol20221`.`PUESTO`, '-', `divpol20221`.`nompue`), '') /* PUESTO */" => "PUESTO",
		"`lideres`.`CELULAR`" => "CELULAR",
		"`lideres`.`DIRECCION`" => "DIRECCION",
		"`lideres`.`CORREO`" => "CORREO",
		"`lideres`.`OBSERVACIONES`" => "OBSERVACIONES",
		"`lideres`.`ESTADO`" => "ESTADO",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['PUESTO' => 'PUESTO', ];

	$x->QueryFrom = "`lideres` LEFT JOIN `divpol2022` as divpol20221 ON `divpol20221`.`PUESTO`=`lideres`.`PUESTO` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'lideres_view.php';
	$x->TableTitle = 'lideres';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`lideres`.`CEDULA`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['LIDER', 'CEDULA', 'NOMBRE', 'PUESTO', 'CELULAR', 'DIRECCION', 'CORREO', 'OBSERVACIONES', 'ESTADO', ];
	$x->ColFieldName = ['LIDER', 'CEDULA', 'NOMBRE', 'PUESTO', 'CELULAR', 'DIRECCION', 'CORREO', 'OBSERVACIONES', 'ESTADO', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/lideres_templateTV.html';
	$x->SelectedTemplate = 'templates/lideres_templateTVS.html';
	$x->TemplateDV = 'templates/lideres_templateDV.html';
	$x->TemplateDVP = 'templates/lideres_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: lideres_init
	$render = true;
	if(function_exists('lideres_init')) {
		$args = [];
		$render = lideres_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: lideres_header
	$headerCode = '';
	if(function_exists('lideres_header')) {
		$args = [];
		$headerCode = lideres_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: lideres_footer
	$footerCode = '';
	if(function_exists('lideres_footer')) {
		$args = [];
		$footerCode = lideres_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
